import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const workerRoot = fileURLToPath(new URL('..', import.meta.url));

test('container contract pins every binary source and runs as a numeric non-root user', async () => {
  const dockerfile = await readFile(new URL('../Dockerfile', import.meta.url), 'utf8');
  const toolchain = JSON.parse(await readFile(new URL('../container-toolchain.json', import.meta.url), 'utf8'));
  assert.match(dockerfile, /node@sha256:e484ae3f1e3c378021c967fd42254f343c302a9263e412280eac32bf5bca7008/u);
  assert.match(dockerfile, /postgres@sha256:45cd22f8d32e189d245403954882f88e7a8714301fda80dab6da90f1265b25a3/u);
  assert.match(dockerfile, /ADD --checksum=sha256:3a379bb6ce47ca7c175999ed44a8f386cc89a9b9e450774b69d98a2c45c5189b/u);
  assert.match(dockerfile, /USER 10001:10001/u);
  assert.match(dockerfile, /\/usr\/share\/doc\/ffmpeg\/LICENSE\.txt/u);
  assert.match(dockerfile, /ANNOTATED_WORKER_TIMEOUT_MS=600000/u);
  assert.match(dockerfile, /ENTRYPOINT \["node", "\/opt\/annotated\/src\/entrypoint\/main\.mjs"\]/u);
  assert.doesNotMatch(dockerfile, /SERVICE_ROLE|DISPATCH_SECRET|DATABASE_URL/u);
  assert.equal(toolchain.runtime.one_media_per_worker_process, true);
  assert.equal(toolchain.runtime.uid, 10001);
  assert.equal(toolchain.ffmpeg.version, 'n8.1.2-44-g7c533d0f86-20260816');
  assert.equal(typeof workerRoot, 'string');
});

test('container context excludes tests and does not include environment or credential files', async () => {
  const ignore = await readFile(new URL('../.dockerignore', import.meta.url), 'utf8');
  assert.match(ignore, /^test$/mu);
  assert.doesNotMatch(ignore, /!.*env/u);
  const dockerfile = await readFile(new URL('../Dockerfile', import.meta.url), 'utf8');
  assert.match(dockerfile, /COPY --chown=10001:10001 src \.\/src/u);
  assert.doesNotMatch(dockerfile, /COPY \. /u);
});

test('Local container acceptance is explicit, read-only, bounded, and self-cleaning', async () => {
  const acceptance = await readFile(new URL('./container-acceptance.mjs', import.meta.url), 'utf8');
  assert.match(acceptance, /ANNOTATED_C5_CONTAINER_LOCAL/u);
  assert.match(acceptance, /'--read-only'/u);
  assert.match(acceptance, /'\/tmp:rw,noexec,nosuid,nodev,size=64m'/u);
  assert.match(acceptance, /'--cap-drop', 'ALL'/u);
  assert.match(acceptance, /'--security-opt', 'no-new-privileges:true'/u);
  assert.match(acceptance, /'--pids-limit', '128'/u);
  assert.match(acceptance, /'--memory', '512m'/u);
  assert.match(acceptance, /'--cpus', '2'/u);
  assert.match(acceptance, /'--env-file', environmentPath/u);
  assert.match(acceptance, /delete from public\.annotations/u);
  assert.match(acceptance, /await rm\(temporaryDirectory, \{ recursive: true, force: true \}\)/u);
});

test('C6 Staging adapters are pinned to exact provider, project, region, and one-task dispatch boundaries', async () => {
  const config = await readFile(new URL('../src/runtime/config.mjs', import.meta.url), 'utf8');
  const dispatch = await readFile(new URL('../src/runtime/cloud-run-dispatch.mjs', import.meta.url), 'utf8');
  const transcriber = await readFile(new URL('../src/transcription/openai-whisper-transcriber.mjs', import.meta.url), 'utf8');
  assert.match(config, /nkkunkwirvfwhmpwonqz/u);
  assert.match(config, /aws-0-us-east-1\.pooler\.supabase\.com/u);
  assert.match(config, /annotated-504301/u);
  assert.match(config, /us-east4/u);
  assert.match(dispatch, /taskCount: 1/u);
  assert.match(dispatch, /timeout: '600s'/u);
  assert.match(transcriber, /https:\/\/api\.openai\.com\/v1\/audio\/transcriptions/u);
  assert.match(transcriber, /OPENAI_WHISPER_MODEL = 'whisper-1'/u);
  const dockerfile = await readFile(new URL('../Dockerfile', import.meta.url), 'utf8');
  assert.doesNotMatch(dockerfile, /OPENAI_API_KEY|SUPABASE_SECRET_KEY/u);
});

test('C6 crash acceptance is explicit, Staging-pinned, six-boundary, and excluded from the image', async () => {
  const acceptance = await readFile(new URL('./staging-crash-acceptance.mjs', import.meta.url), 'utf8');
  assert.match(acceptance, /ANNOTATED_C6_STAGING_CRASH/u);
  assert.match(acceptance, /https:\/\/nkkunkwirvfwhmpwonqz\.supabase\.co/u);
  assert.match(acceptance, /aws-0-us-east-1\.pooler\.supabase\.com/u);
  for (const boundary of [
    'after_claim',
    'after_derivative_upload',
    'after_derivative_stage',
    'after_transcript_stage',
    'after_raw_delete',
    'after_raw_confirm',
  ]) assert.match(acceptance, new RegExp(`${boundary}:`, 'u'));
  assert.match(acceptance, /return:minimal|return=minimal/u);
  assert.match(acceptance, /await api\(`\/rest\/v1\/annotations\?id=eq\./u);
  assert.doesNotMatch(acceptance, /vnxjktpdzmykmqrqwvks|Annotated Production/u);
  const ignore = await readFile(new URL('../.dockerignore', import.meta.url), 'utf8');
  assert.match(ignore, /^test$/mu);
});

test('C6 90-second acceptance is exact-ref, paused-schedule, immutable-image, bounded, and self-cleaning', async () => {
  const acceptance = await readFile(new URL('./staging-duration-acceptance.mjs', import.meta.url), 'utf8');
  const runner = await readFile(new URL('./run-c6-duration-gate.ps1', import.meta.url), 'utf8');
  const generator = await readFile(new URL('./generate-c6-duration-fixture.ps1', import.meta.url), 'utf8');
  const acquisition = await readFile(new URL('./get-c6-supabase-cli.ps1', import.meta.url), 'utf8');
  const authorization = await readFile(new URL('./authorize-c6-supabase-cli.ps1', import.meta.url), 'utf8');
  const diagnostic = await readFile(new URL('./run-c6-duration-diagnostic.ps1', import.meta.url), 'utf8');
  const recovery = await readFile(new URL('./run-c6-duration-recovery.ps1', import.meta.url), 'utf8');
  const finalizer = await readFile(new URL('./finalize-c6-duration-gate.ps1', import.meta.url), 'utf8');
  const correctiveDeployment = await readFile(new URL('./build-deploy-c6-duration-fix.ps1', import.meta.url), 'utf8');
  const tailClampProbe = await readFile(new URL('./c6-tail-clamp-container-probe.mjs', import.meta.url), 'utf8');
  assert.match(acceptance, /ANNOTATED_C6_STAGING_DURATION/u);
  assert.match(acceptance, /https:\/\/nkkunkwirvfwhmpwonqz\.supabase\.co/u);
  assert.match(acceptance, /requested_duration_ms: 90_000/u);
  assert.match(acceptance, /writeFile\(artifactPath, processedBytes, \{ flag: 'wx' \}\)/u);
  assert.match(acceptance, /return=minimal/u);
  assert.match(acceptance, /processing_queue_count/u);
  assert.match(acceptance, /retryScheduled && !awaitingExpectedAttempt \? 3 : 2/u);
  assert.match(acceptance, /diagnostic-export/u);
  assert.match(acceptance, /c6_duration_90000_diagnostic_export/u);
  assert.doesNotMatch(acceptance, /vnxjktpdzmykmqrqwvks|Annotated Production/u);
  assert.match(runner, /nkkunkwirvfwhmpwonqz/u);
  assert.match(runner, /vnxjktpdzmykmqrqwvks/u);
  assert.match(runner, /PSObject\.Properties\['ref'\]/u);
  assert.match(runner, /Get-ProjectReference/u);
  assert.match(runner, /local_project_ref_matches/u);
  assert.match(runner, /PAUSED/u);
  assert.match(runner, /sha256:db5b20136e38284fa03f45292edeb29c398597592e6155d994b09f8fc9cffd57/u);
  assert.match(runner, /annotated-media-dispatcher-staging/u);
  assert.match(runner, /Annotated-supabase-2\.115\.0/u);
  assert.match(runner, /supabaseVersion -ne '2\.115\.0'/u);
  assert.match(runner, /Annotated-supabase-c6-home/u);
  assert.match(runner, /\$env:SUPABASE_HOME = \$supabaseHomePath/u);
  assert.doesNotMatch(runner, /--profile/u);
  assert.match(runner, /run jobs describe annotated-media-worker-staging[^\n]+--format=json/u);
  assert.match(runner, /workerJob\.spec\.template\.spec\.template\.spec\.containers/u);
  assert.match(runner, /workerContainers\.Count -ne 1/u);
  assert.doesNotMatch(runner, /value\([^\n]*containers[^\n]*image\)/u);
  assert.match(runner, /c6_worker_image_identity/u);
  assert.match(runner, /container_count/u);
  assert.match(runner, /image_reference_present/u);
  assert.match(runner, /expected_digest_matches/u);
  assert.match(runner, /jsonPayload\.media_id/u);
  assert.match(runner, /--freshness=2h --limit=50 --order=asc/u);
  assert.match(runner, /\$lastStart = -1/u);
  assert.match(runner, /foreach \(\$logRow in \$parsedLogRows\)/u);
  assert.match(runner, /\$allEvents\[\$index\] -eq 'worker_started'/u);
  assert.match(runner, /json\(jsonPayload\.event,jsonPayload\.stage,jsonPayload\.code,jsonPayload\.outcome\)/u);
  assert.match(runner, /worker_started', 'worker_claimed', 'derivative_staged', 'transcript_staged', 'raw_cleanup_confirmed', 'worker_completed/u);
  assert.match(runner, /c6_duration_90000_logs/u);
  assert.match(runner, /node \$harness cleanup/u);
  assert.match(runner, /statusCode -eq 3/u);
  assert.match(generator, /g7c533d0f86-20260816/u);
  assert.match(generator, /speech_markers_ms/u);
  assert.match(generator, /\$filterComplex = @\(/u);
  assert.match(generator, /\) -join ''/u);
  assert.match(generator, /'-filter_complex', \$filterComplex/u);
  assert.match(acquisition, /https:\/\/github\.com\/supabase\/cli\/releases\/download\/v\$version/u);
  assert.match(acquisition, /a20bc5c8d5d0b03dff637aa98f1758d117811aeed30eb0485ac9ff22b2ada5be/u);
  assert.match(acquisition, /Get-FileHash -Algorithm SHA256/u);
  assert.match(acquisition, /installed_system_wide = \$false/u);
  assert.match(acquisition, /repository_dependency_added = \$false/u);
  assert.match(authorization, /Annotated-supabase-c6-home/u);
  assert.match(authorization, /\$env:SUPABASE_HOME = \$supabaseHomePath/u);
  assert.match(authorization, /& \$Supabase login --no-browser/u);
  assert.doesNotMatch(authorization, /--profile/u);
  assert.match(authorization, /nkkunkwirvfwhmpwonqz/u);
  assert.match(authorization, /vnxjktpdzmykmqrqwvks/u);
  assert.match(authorization, /stagingHealthyAndLinked/u);
  assert.match(authorization, /visible_project_count/u);
  assert.match(authorization, /staging_match_count/u);
  assert.match(authorization, /production_linked/u);
  assert.match(authorization, /\[switch\] \$RunDurationGate/u);
  assert.match(authorization, /\[switch\] \$RunDurationDiagnostic/u);
  assert.match(authorization, /\[switch\] \$RunDurationRecovery/u);
  assert.match(authorization, /\[switch\] \$ObserveDurationRecovery/u);
  assert.match(authorization, /\[switch\] \$FinalizeDurationGate/u);
  assert.match(authorization, /& \$durationGate -Supabase \$Supabase -SupabaseHome \$supabaseHomePath/u);
  assert.match(authorization, /& \$durationDiagnostic/u);
  assert.match(authorization, /& \$durationRecovery -Supabase \$Supabase -SupabaseHome \$supabaseHomePath/u);
  assert.match(authorization, /& \$durationRecovery -Supabase \$Supabase -SupabaseHome \$supabaseHomePath -ObserveExistingDispatch/u);
  assert.match(authorization, /& \$durationFinalize -Supabase \$Supabase -SupabaseHome \$supabaseHomePath/u);
  assert.match(authorization, /global_profile_modified = \$false/u);
  assert.match(diagnostic, /annotated-staging-supabase-secret-key/u);
  assert.match(diagnostic, /annotated-staging-openai-api-key/u);
  assert.match(diagnostic, /diagnostic-export/u);
  assert.match(diagnostic, /staging-openai-structure-diagnostic\.mjs/u);
  assert.match(diagnostic, /Both Staging schedules must remain PAUSED/u);
  assert.match(diagnostic, /no retry dispatched/u);
  assert.doesNotMatch(diagnostic, /run jobs execute|node \$harness cleanup/u);
  assert.match(recovery, /nkkunkwirvfwhmpwonqz/u);
  assert.match(recovery, /sha256:db5b20136e38284fa03f45292edeb29c398597592e6155d994b09f8fc9cffd57/u);
  assert.match(recovery, /c6530000-0000-4000-8000-000000000001/u);
  assert.match(recovery, /node \$harness recovery-preflight/u);
  assert.match(recovery, /\[switch\] \$ObserveExistingDispatch/u);
  assert.match(recovery, /if \(\$ObserveExistingDispatch\)/u);
  assert.match(recovery, /dispatcher_executed_by_this_run = \$false/u);
  assert.match(recovery, /run jobs execute annotated-media-dispatcher-staging/u);
  assert.doesNotMatch(recovery, /run jobs execute annotated-media-worker-staging/u);
  assert.match(recovery, /node \$harness recovery-status/u);
  assert.match(recovery, /node \$harness cleanup/u);
  assert.match(recovery, /schedules_paused = \$true/u);
  assert.match(recovery, /production_accessed = \$false/u);
  assert.doesNotMatch(recovery, /scheduler jobs resume/u);
  assert.match(recovery, /Production unexpectedly appears linked/u);
  assert.match(acceptance, /c6_duration_90000_recovery_preflight/u);
  assert.match(acceptance, /a07a5f22dc27e7b41d49a716654b4f4ca147630f3d55dbd135f80ab45111d70e/u);
  assert.match(acceptance, /expectedAttempt: 2/u);
  assert.match(acceptance, /expectedChecksum: RETAINED_PROCESSED_SHA256/u);
  assert.match(acceptance, /attemptCount < expectedAttempt/u);
  assert.match(acceptance, /awaiting_expected_attempt: awaitingExpectedAttempt/u);
  assert.match(acceptance, /resume-status/u);
  assert.match(acceptance, /exportArtifact: false/u);
  assert.match(acceptance, /acceptance_artifact_matches/u);
  assert.match(finalizer, /nkkunkwirvfwhmpwonqz/u);
  assert.match(finalizer, /sha256:db5b20136e38284fa03f45292edeb29c398597592e6155d994b09f8fc9cffd57/u);
  assert.match(finalizer, /node \$harness resume-status/u);
  assert.match(finalizer, /c6_duration_90000_logs/u);
  assert.match(finalizer, /node \$harness cleanup/u);
  assert.match(finalizer, /dispatcher_executed = \$false/u);
  assert.match(finalizer, /worker_executed = \$false/u);
  assert.doesNotMatch(finalizer, /run jobs execute|node \$harness prepare|generate-c6-duration-fixture/u);
  assert.match(correctiveDeployment, /docker build --pull=false --platform=linux\/amd64/u);
  assert.match(correctiveDeployment, /docker image ls --filter "reference=\$LocalTag"/u);
  assert.doesNotMatch(correctiveDeployment, /docker image inspect \$LocalTag \*> \$null/u);
  assert.match(correctiveDeployment, /\[switch\] \$ResumeExistingCandidate/u);
  assert.match(correctiveDeployment, /docker-credential-gcloud\.cmd/u);
  assert.match(correctiveDeployment, /\$originalProcessPath = \$env:PATH/u);
  assert.match(correctiveDeployment, /\$env:PATH = "\$gcloudBin\$\(\[System\.IO\.Path\]::PathSeparator\)\$originalProcessPath"/u);
  assert.match(correctiveDeployment, /\$env:PATH = \$originalProcessPath/u);
  assert.match(correctiveDeployment, /system_path_modified = \$false/u);
  assert.match(correctiveDeployment, /10001:10001/u);
  assert.match(correctiveDeployment, /\$runtimeConstraints = @\('--rm', '--network', 'none', '--read-only'/u);
  assert.match(correctiveDeployment, /--entrypoint \/usr\/bin\/id/u);
  assert.match(correctiveDeployment, /--entrypoint \/usr\/local\/bin\/node/u);
  assert.match(correctiveDeployment, /c6_corrective_ffmpeg_runtime_probe/u);
  assert.match(correctiveDeployment, /pinned_version_present/u);
  assert.match(correctiveDeployment, /n8\\\.1\\\.2-44-g7c533d0f86-20260816/u);
  assert.match(correctiveDeployment, /type=bind,source=\$tailClampProbePath,target=\/opt\/c6-tail-clamp-container-probe\.mjs,readonly/u);
  assert.match(correctiveDeployment, /--mount \$tailClampProbeMount/u);
  assert.doesNotMatch(correctiveDeployment, /--eval/u);
  assert.match(tailClampProbe, /end_ms: 90_400/u);
  assert.match(tailClampProbe, /result\[0\]\.end_ms !== 90_000/u);
  assert.match(tailClampProbe, /end_ms: 10_160/u);
  assert.match(tailClampProbe, /end_ms: 11_001/u);
  assert.doesNotMatch(correctiveDeployment, /--entrypoint \/bin\/sh/u);
  assert.match(correctiveDeployment, /annotated-media-worker-staging/u);
  assert.match(correctiveDeployment, /annotated-media-dispatcher-staging/u);
  assert.match(correctiveDeployment, /annotated-media-reconciler-staging/u);
  assert.match(correctiveDeployment, /Both Staging schedules must remain PAUSED/u);
  assert.match(correctiveDeployment, /execution_performed = \$false/u);
  assert.match(correctiveDeployment, /production_accessed = \$false/u);
  assert.doesNotMatch(correctiveDeployment, /run jobs execute|scheduler jobs resume|vnxjktpdzmykmqrqwvks/u);
  const ignore = await readFile(new URL('../.dockerignore', import.meta.url), 'utf8');
  assert.match(ignore, /^test$/mu);
});

test('C6 codec acceptance is VP8/Opus-specific, Staging-pinned, bounded, and self-cleaning', async () => {
  const acceptance = await readFile(new URL('./staging-codec-acceptance.mjs', import.meta.url), 'utf8');
  const runner = await readFile(new URL('./run-c6-codec-gate.ps1', import.meta.url), 'utf8');
  const generator = await readFile(new URL('./generate-c6-vp8-codec-fixture.ps1', import.meta.url), 'utf8');
  const authorization = await readFile(new URL('./authorize-c6-supabase-cli.ps1', import.meta.url), 'utf8');
  assert.match(acceptance, /ANNOTATED_C6_STAGING_CODEC/u);
  assert.match(acceptance, /https:\/\/nkkunkwirvfwhmpwonqz\.supabase\.co/u);
  assert.match(acceptance, /video\/webm;codecs=vp8,opus/u);
  assert.match(acceptance, /rawVideo\?\.codec_name !== 'vp8'/u);
  assert.match(acceptance, /processed_mime_type === 'video\/mp4'/u);
  assert.match(acceptance, /Number\(media\.width\) === 426/u);
  assert.match(acceptance, /writeFile\(artifactPath, processedBytes, \{ flag: 'wx' \}\)/u);
  assert.match(acceptance, /node|return=minimal/u);
  assert.match(runner, /nkkunkwirvfwhmpwonqz/u);
  assert.match(runner, /vnxjktpdzmykmqrqwvks/u);
  assert.match(runner, /PAUSED/u);
  assert.match(runner, /sha256:db5b20136e38284fa03f45292edeb29c398597592e6155d994b09f8fc9cffd57/u);
  assert.match(runner, /run jobs execute annotated-media-dispatcher-staging/u);
  assert.match(runner, /node \$harness cleanup/u);
  assert.match(runner, /c6_codec_vp8_logs/u);
  assert.doesNotMatch(runner, /scheduler jobs resume|vnxjktpdzmykmqrqwvks.*run jobs/u);
  assert.match(generator, /g7c533d0f86-20260816/u);
  assert.match(generator, /-c:v libvpx/u);
  assert.match(generator, /-c:a libopus/u);
  assert.match(authorization, /\[switch\] \$RunCodecGate/u);
  assert.match(authorization, /& \$codecGate -Supabase \$Supabase -SupabaseHome \$supabaseHomePath/u);
});

test('C6 geometry acceptance is matrix-bounded, fail-closed, immutable-image pinned, and self-cleaning', async () => {
  const geometry = await readFile(new URL('../src/media/geometry.mjs', import.meta.url), 'utf8');
  const acceptance = await readFile(new URL('./staging-geometry-acceptance.mjs', import.meta.url), 'utf8');
  const runner = await readFile(new URL('./run-c6-geometry-gate.ps1', import.meta.url), 'utf8');
  const generator = await readFile(new URL('./generate-c6-geometry-fixture.ps1', import.meta.url), 'utf8');
  const deployment = await readFile(new URL('./build-deploy-c6-geometry-fix.ps1', import.meta.url), 'utf8');
  const providerTailDeployment = await readFile(new URL('./build-deploy-c6-provider-tail-fix.ps1', import.meta.url), 'utf8');
  const diagnostic = await readFile(new URL('./run-c6-geometry-diagnostic.ps1', import.meta.url), 'utf8');
  const recovery = await readFile(new URL('./run-c6-geometry-recovery.ps1', import.meta.url), 'utf8');
  const structureDiagnostic = await readFile(new URL('./staging-openai-structure-diagnostic.mjs', import.meta.url), 'utf8');
  const authorization = await readFile(new URL('./authorize-c6-supabase-cli.ps1', import.meta.url), 'utf8');
  assert.match(geometry, /-CSS_TOLERANCE/u);
  assert.match(acceptance, /ANNOTATED_C6_STAGING_GEOMETRY/u);
  assert.match(acceptance, /https:\/\/nkkunkwirvfwhmpwonqz\.supabase\.co/u);
  assert.match(acceptance, /portrait|letterbox|unsafe/u);
  assert.match(acceptance, /attempt_count: scenario\.terminalFailure \? 2 : 0/u);
  assert.match(acceptance, /failure_code === 'unsafe_geometry'/u);
  assert.match(acceptance, /annotationRows\[0\]\.status === 'draft'/u);
  assert.match(acceptance, /no_processed_object/u);
  assert.match(acceptance, /raw_retained_for_terminal_cleanup/u);
  assert.match(acceptance, /writeFile\(artifactPath, processedBytes, \{ flag: 'wx' \}\)/u);
  assert.match(runner, /sha256:f4b101880bbdf77784769f82fe5055261537f0fb6f868252b3891eb687d7b057/u);
  assert.match(runner, /nkkunkwirvfwhmpwonqz/u);
  assert.match(runner, /vnxjktpdzmykmqrqwvks/u);
  assert.match(runner, /PAUSED/u);
  assert.match(runner, /\$cases = if \(\$SkipPortrait\) \{ @\('letterbox', 'unsafe'\) \}/u);
  assert.match(runner, /node \$harness cleanup/u);
  assert.match(runner, /worker_started', 'worker_claimed', 'worker_failed/u);
  assert.doesNotMatch(runner, /scheduler jobs resume/u);
  assert.match(generator, /ValidateSet\('portrait', 'letterbox', 'unsafe'\)/u);
  assert.match(generator, /c=magenta/u);
  assert.match(generator, /libvpx-vp9/u);
  assert.match(deployment, /c6_geometry_tolerance_deployment/u);
  assert.match(deployment, /c6-geometry-tolerance-container-probe\.mjs/u);
  assert.match(providerTailDeployment, /c6_provider_tail_2s_deployment/u);
  assert.match(providerTailDeployment, /c6-provider-tail-2s-candidate/u);
  assert.match(authorization, /\[switch\] \$RunGeometryGate/u);
  assert.match(authorization, /& \$geometryGate -Supabase \$Supabase -SupabaseHome \$supabaseHomePath/u);
  assert.match(authorization, /\[switch\] \$RunGeometryDiagnostic/u);
  assert.match(authorization, /& \$geometryDiagnostic/u);
  assert.match(authorization, /\[switch\] \$RunGeometryRecovery/u);
  assert.match(authorization, /& \$geometryRecovery -Supabase \$Supabase -SupabaseHome \$supabaseHomePath/u);
  assert.match(acceptance, /c6_geometry_portrait_diagnostic_export/u);
  assert.match(acceptance, /c6_geometry_portrait_recovery_preflight/u);
  assert.match(acceptance, /annotation_transcripts\?select=annotation_id&annotation_id=eq\./u);
  assert.doesNotMatch(acceptance, /annotation_transcripts\?select=id&annotation_id=eq\./u);
  assert.match(acceptance, /fd0c97f6c50b2655c43e44e68db86ef639c7cee9f8ccd20940602ab7c4ea387a/u);
  assert.match(acceptance, /expectedAttempt: 2/u);
  assert.match(acceptance, /retained_derivative_reused/u);
  assert.match(diagnostic, /ANNOTATED_GEOMETRY_CASE = 'portrait'/u);
  assert.match(diagnostic, /ANNOTATED_C6_DERIVATIVE_MEDIA_TYPE = 'video'/u);
  assert.match(diagnostic, /no retry dispatched/u);
  assert.doesNotMatch(diagnostic, /run jobs execute|node \$harness cleanup/u);
  assert.match(recovery, /sha256:f4b101880bbdf77784769f82fe5055261537f0fb6f868252b3891eb687d7b057/u);
  assert.match(recovery, /node \$harness recovery-preflight/u);
  assert.match(recovery, /node \$harness recovery-status/u);
  assert.match(recovery, /-SkipPortrait/u);
  assert.match(recovery, /retained_derivative_reused = \$true/u);
  assert.doesNotMatch(recovery, /scheduler jobs resume/u);
  assert.match(structureDiagnostic, /ANNOTATED_C6_DERIVATIVE_MEDIA_TYPE/u);
});

test('C6 Local audio-quality gate is 90-second, three-by-three, signal-bounded, and blind-listening ready', async () => {
  const quality = await readFile(new URL('./run-c6-audio-quality-local.mjs', import.meta.url), 'utf8');
  assert.match(quality, /const REQUESTED_DURATION_MS = 90_000/u);
  assert.match(quality, /audio-opus64/u);
  assert.match(quality, /vp9-opus64/u);
  assert.match(quality, /vp8-opus96/u);
  assert.match(quality, /const frequencies = Object\.freeze\(\[/u);
  assert.match(quality, /sampleIndex === variantIndex/u);
  assert.match(quality, /maximum_step <= 4_096/u);
  assert.match(quality, /large_step_count === 0/u);
  assert.match(quality, /minimum_to_median_window_rms_ratio >= 0\.65/u);
  assert.match(quality, /channel_rms_ratio <= 1\.25/u);
  assert.match(quality, /blind-map\.json/u);
  assert.match(quality, /keep_blind_until_owner_results: true/u);
  assert.match(quality, /Annotated-c6-audio-quality-local/u);
  assert.doesNotMatch(quality, /fetch\(|https?:\/\//u);
});

test('C6 retention gate is exact-Staging, paused-schedule, fixture-bounded, and cleanup-complete', async () => {
  const [acceptance, runner] = await Promise.all([
    readFile(new URL('./staging-retention-acceptance.mjs', import.meta.url), 'utf8'),
    readFile(new URL('./run-c6-retention-gate.ps1', import.meta.url), 'utf8'),
  ]);
  assert.match(acceptance, /https:\/\/nkkunkwirvfwhmpwonqz[.]supabase[.]co/u);
  assert.match(acceptance, /processing_status: 'removed'/u);
  assert.match(acceptance, /processing_status: 'failed'/u);
  assert.match(acceptance, /raw_storage_path: null, raw_deleted_at:/u);
  assert.match(acceptance, /updated_at: failedUpdatedAt/u);
  assert.match(acceptance, /annotationStatus \}\) => annotationStatus === 'draft'/u);
  assert.match(acceptance, /content_cleared_at != null/u);
  assert.match(acceptance, /transcript_text == null/u);
  assert.match(acceptance, /objects\.every\(\(present\) => !present\)/u);
  assert.match(runner, /nkkunkwirvfwhmpwonqz/u);
  assert.match(runner, /vnxjktpdzmykmqrqwvks/u);
  assert.match(runner, /annotated-media-reconciler-staging/u);
  assert.match(runner, /git status --porcelain/u);
  assert.match(runner, /origin\/codex\/phase-c-worker/u);
  assert.match(runner, /PAUSED/u);
  assert.match(runner, /run[.]googleapis[.]com%2Fstdout/u);
  assert.match(runner, /run[.]googleapis[.]com\/execution_name/u);
  assert.match(runner, /removed_cleanup/u);
  assert.match(runner, /terminal_raw_cleanup/u);
  assert.match(runner, /node \$harness cleanup/u);
  assert.doesNotMatch(runner, /scheduler jobs resume|annotated-media-dispatcher-staging.*execute/u);
});

test('C6 browser audio matrix is localhost-only, six-variant, three-sample, and bypasses hosted upload truthfully', async () => {
  const runner = await readFile(new URL('./run-c6-browser-audio-matrix.mjs', import.meta.url), 'utf8');
  const collector = await readFile(new URL('./local-acceptance/c6-browser-capture-collector.mjs', import.meta.url), 'utf8');
  const offscreen = await readFile(new URL('../../extension/entrypoints/offscreen/main.ts', import.meta.url), 'utf8');
  const diagnostic = await readFile(new URL('../../extension/utils/c6-capture-diagnostic.ts', import.meta.url), 'utf8');
  for (const variant of [
    'vp9-default', 'loopback-off', 'timeslice-none',
    'vp8-default', 'vp9-explicit', 'vp8-explicit',
  ]) assert.match(runner, new RegExp(`'${variant}'`, 'u'));
  assert.match(collector, /sample > 3/u);
  assert.match(collector, /requested_duration_ms === 90_000/u);
  assert.match(collector, /requested_duration_not_exactly_90000_ms/u);
  assert.match(collector, /127\.0\.0\.1/u);
  assert.match(collector, /250_000_000/u);
  assert.match(collector, /checksum_sha256/u);
  assert.match(diagnostic, /collectorUrl: null/u);
  assert.match(diagnostic, /loopbackEnabled: true/u);
  assert.match(diagnostic, /timesliceMs: 1_000/u);
  assert.match(diagnostic, /\['localhost', '127\.0\.0\.1'\]/u);
  assert.match(offscreen, /if \(C6_DIAGNOSTIC\.enabled && C6_DIAGNOSTIC\.collectorUrl\)/u);
  assert.match(offscreen, /Local diagnostic capture ended without a hosted-media upload/u);
  assert.match(runner, /c6_browser_exact_player_position/u);
  assert.doesNotMatch(runner, /nkkunkwirvfwhmpwonqz|gcloud|run jobs|docker push/u);
  assert.doesNotMatch(collector, /service_role|SUPABASE|OPENAI|https:\/\//u);
  const analysis = await readFile(new URL('./run-c6-browser-audio-analysis.mjs', import.meta.url), 'utf8');
  assert.match(analysis, /createLocalDerivative/u);
  assert.match(analysis, /requested_duration_ms === REQUESTED_DURATION_MS/u);
  assert.match(analysis, /captures\.length !== 3/u);
  assert.match(analysis, /browser-blind-map\.json/u);
  assert.match(analysis, /keep_blind_until_owner_results: true/u);
  assert.match(analysis, /derivative\.dropout_window_count <= raw\.dropout_window_count \+ 2/u);
  assert.doesNotMatch(analysis, /fetch\(|https?:\/\//u);
});
